language: c
dist: bionic

notifications:
  email: false
arch:
    - amd64
    - arm64
before_install:
  sudo apt-get install -y libsqlite3-dev cppcheck valgrind gcc-4.8 gettext libc6-dev-armhf-cross libc6-dev-arm64-cross gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf qemu-user-static binfmt-support libsecp256k1-dev

env:
  - ARCH=64 SOURCE_CHECK_ONLY=true COPTFLAGS="-O3"
  
cache:
  directories:
    - dependencies
    - external

script:
  .travis/build.sh
